version: '3.7'

services:
  kafka-dc:
    image: kafka-dc
    build: .
    container_name: kafka-dc
    ports:
      - "127.0.0.1:2181:2181"
      - "127.0.0.1:9092:9092"
    volumes:
      - ~/Dev/Docker/logs/kafka:/opt/kafka/server/logs