server:
  port: 8485

mcp:
  zipkin:
    url: http://127.0.0.1:9411/api/v2/spans

spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/ordering
    username: ordering
    password: ordering
  jpa:
    show-sql: true
