server:
  port: 8485

kafka:
  bootstrapAddress: localhost:9092
  clientId: topics

spring:
  datasource:
    url: jdbc:postgresql://localhost:5442/ordering
    username: ordering
    password: ordering
  jpa:
    show-sql: true
  zipkin:
    base-url: http://127.0.0.1:9411
