server:
  port: 8484

external:
  api:
    contractorUrl: http://127.0.0.1:8485/ordering

mcp:
  zipkin:
    url: http://127.0.0.1:9411/api/v2/spans

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/ordering
    username: ordering
    password: ordering
  jpa:
    show-sql: true
