CREATE DATABASE paying;

CREATE USER paying WITH PASSWORD 'paying';

ALTER USER paying WITH SUPERUSER;

GRANT ALL PRIVILEGES ON DATABASE paying TO paying;
GRANT ALL PRIVILEGES ON SCHEMA public TO paying;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO paying;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO paying;

SET TIME ZONE 'America/Montreal';
SET TIMEZONE TO 'America/Montreal';
ALTER DATABASE paying SET timezone TO 'America/Montreal';

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
