version: '3.1'

services:
  paying-db:
    container_name: paying-db-standalone
    restart: always
    image: paying-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5443:5432"
