version: '3.7'

services:
  ordering-db:
    image: ordering-db
    container_name: ordering-dc-db
    healthcheck:
      test: "exit 0"
    ports:
      - "5440:5432"
  ordering-server:
    image: ordering-server
    build: .
    container_name: ordering-dc-server
    depends_on:
      - ordering-db
    ports:
      - "127.0.0.1:8485:8485"
    volumes:
      - ~/Dev/Docker/logs/ordering:/opt/ordering/server/logs
    environment:
      # Spring running profile
      - springProfile=docker

      # Application running port
      - serverPort=8485

      # DB configuration
      - databaseUrl=jdbc:postgresql://ordering-db:5432/ordering
      - databaseUsername=ordering
      - databasePassword=ordering

      # JPA sql logging
      - jpaShowSql=true

      # Tracing
      - mcp.zipkin=http://tracer-dc:9411

      # Kafka
      - serverHost=http://kafka-dc:9092
      - zookeeperHost=http://kafka-dc:2181
      - clientId=topics

