server:
  port: 8486

kafka:
  serverHost: localhost:9092
  clientId: topics

spring:
  datasource:
    url: jdbc:postgresql://localhost:5443/paying
    username: paying
    password: paying
  jpa:
    show-sql: true
  zipkin:
    base-url: http://127.0.0.1:9411
