server:
  port: 8486

mcp:
  zipkin:
    url: http://127.0.0.1:9411/api/v2/spans

spring:
  datasource:
    url: jdbc:postgresql://localhost:5443/paying
    username: paying
    password: paying
  jpa:
    show-sql: true
